<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'; import { api } from '../api';
const data=ref<any>({weeks:[],rows:[]}),selected=ref<any>(null),q=ref('all');
async function load(){data.value=await api('/admin/settlement/history?preset='+q.value)} onMounted(load);
const stats=computed(()=>({weeks:data.value.weeks.length,granted:data.value.rows.filter((x:any)=>x.status==='GRANTED').length,revoked:data.value.rows.filter((x:any)=>x.status==='REVOKED').length,total:data.value.rows.length}));
const names:any={today:'今天','7d':'近 7 天','30d':'近 30 天',month:'本月',all:'全部'};
</script>
<template><div><div class="hdr">榜单历史记录 <em>全周期结算快照 · 共 {{stats.weeks}} 个已结算周次</em></div><section class="card filter"><b>筛选</b><button v-for="x in ['today','7d','30d','month','all']" :key="x" class="btn" :class="{ghost:q!==x}" @click="q=x;load()">{{names[x]}}</button></section><div class="stats"><section class="card"><span>结算周次</span><b>{{stats.weeks}}</b></section><section class="card"><span>已发放奖励</span><b>{{stats.granted}}</b></section><section class="card"><span>已撤销</span><b class="red">{{stats.revoked}}</b></section><section class="card"><span>发放总量</span><b>{{stats.total}}</b></section></div><section class="card"><table class="tb2"><thead><tr><th>周次</th><th>获奖人数</th><th>战队奖</th><th>个人奖</th><th>手动补发</th><th>已发放</th><th>已撤销</th><th>操作</th></tr></thead><tbody><tr v-for="w in data.weeks" :key="w.week"><td><b>{{w.week}}</b></td><td>{{w.winners}} 人</td><td>{{w.team}}</td><td>{{w.personal}}</td><td>{{w.manual||'—'}}</td><td class="green">{{w.granted}}</td><td class="red">{{w.revoked||0}}</td><td><button class="btn ghost mini" @click="selected=w">查看明细</button></td></tr><tr v-if="!data.weeks.length"><td colspan="8" class="table-empty">当前筛选范围内无结算历史</td></tr></tbody></table></section><div v-if="selected" class="mask" @click.self="selected=null"><section class="dialog"><div class="st">{{selected.week}} 结算明细</div><div v-for="r in selected.rows" :key="r.id" class="line">{{r.nick}} · {{r.desc}} · {{r.status==='GRANTED'?'已发放':r.status==='REVOKED'?'已撤销':'未通过'}}</div><div v-if="!selected.rows?.length" class="list-empty">该周期暂无结算明细</div><button class="btn ghost" @click="selected=null">关闭</button></section></div><div class="note">快照原则：历史周次按结算当时规则保存，后续修改奖励规则不影响已结算记录。</div></div></template>
<style scoped>.filter{display:flex;gap:10px;align-items:center}.filter .btn{padding:6px 12px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:12px 0}.stats .card span,.stats .card b{display:block}.stats b{font-size:25px;margin-top:8px}.green{color:#3B6D11}.red{color:#B52B2B}.mini{padding:5px 10px;font-size:12px}.mask{position:fixed;inset:0;z-index:30;display:grid;place-items:center;background:#0006}.dialog{width:min(560px,90%);background:#fff;border-radius:14px;padding:20px}.line{padding:9px 0;border-bottom:1px solid var(--line)}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}}</style>
